services:
    # default configuration for services in *this* file
    App\Http\FinanceApiInterface:
        class: App\Http\FakeApiFinanceClient
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
